### ISSUE TITLE
无法下单编程器电路

### ISSUE THREAD

**Issue by Koamasi** [reobf/Programmable-Hatches-Mod#129]
无法下单蓝框电路
![33cf8667a38d9724c4f625b7f7d8c030](https://github.com/user-attachments/assets/8b79161d-f35b-49aa-bb9a-916678972502)
具体的后台报错信息如下
[22:54:46] [Server thread/ERROR] [AE2:S]: Error while simulating crafting for CraftingRequest{request=30xitem.prog_circuit@0<Programming Circuit (Programmed Circuit)>, substitutionMode=PRECISE_FRESH, remainingToProcess=30, byteCost=0, wasSimulated=false, incomplete=false}
java.lang.ArithmeticException: / by zero
        at Launch//appeng.crafting.v2.resolvers.CraftableItemResolver$CraftFromPatternTask.calculateOneStep(CraftableItemResolver.java:327) ~[CraftableItemResolver$CraftFromPatternTask.class:?]
        at Launch//appeng.crafting.v2.CraftingContext.doWork(CraftingContext.java:291) ~[CraftingContext.class:?]
        at Launch//appeng.crafting.v2.CraftingJobV2.simulateFor(CraftingJobV2.java:203) ~[CraftingJobV2.class:?]
        at Launch//appeng.hooks.TickHandler.lambda$onTick$1(TickHandler.java:173) ~[TickHandler.class:?]
        at java.base/java.util.Collection.removeIf(Collection.java:583) [?:?]
        at Launch//appeng.hooks.TickHandler.onTick(TickHandler.java:173) [TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_839_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
        at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
        at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at Launch//cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by reobf** [comment]
gtnh版本

**Comment by Koamasi** [comment]
是2.7.0 mod版本是0.1.1p2

**Comment by reobf** [comment]
能传一下日志吗

下单电路就能复现吗？

**Comment by reobf** [comment]
[15:57:38] [main/DEBUG] [org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper/]: Scanning file:/E:/GT_New_Horizons_2.6.1_Server_Java_17-21/mods/vmtweak-0.0.1.jar for mixin tweaker

你应该下载这个https://github.com/reobf/Void-Miner-Tweak-Mod/releases/tag/v0.0.2-GTNH270

**Comment by Koamasi** [comment]
oo也是这个问题啊 okok

**Comment by reobf** [comment]
你先试完再关issue

**Comment by reobf** [comment]
不是 270你还装ZeroPointBugfix？

**Comment by Koamasi** [comment]
a?我没装啊🤔

**Comment by reobf** [comment]
E:\GT_New_Horizons_2.6.1_Server_Java_17-21\mods\ZeroPointBugfix-0.6.3.jar

**Comment by reobf** [comment]
不对 看错了

**Comment by Koamasi** [comment]
遐思 我还以为我传错日志了😰

**Comment by Koamasi** [comment]
能正常下单蓝框电路了

**Comment by reobf** [comment]
> 能正常下单蓝框电路了

哦哦不是 我捋清楚了
你没下错 是我先上传的0.0.2 再传的0.0.1和0.0.2-gtnh270

然后我日志看岔了 外打正着了

**Comment by reobf** [comment]
反正...解决就好

这边浏览器下载日志一堆
（2）.2 副本（2）
这种后缀 弄错了
