### ISSUE TITLE
物品充足但是ae的东西发配不到任何输入总线或者可编程舱室 总成之类的

### ISSUE THREAD

**Issue by xfpuls** [reobf/Programmable-Hatches-Mod#47]
Error while simulating crafting for CraftingRequest{request=1xitem.fluid_drop@0<drop of Sulfur Dioxide>, substitutionMode=PRECISE_FRESH, remainingToProcess=1, byteCost=0, wasSimulated=false, incomplete=false}
java.lang.ArithmeticException: / by zero
        at appeng.crafting.v2.resolvers.CraftableItemResolver$CraftFromPatternTask.calculateOneStep(CraftableItemResolver.java:273) ~[CraftableItemResolver$CraftFromPatternTask.class:?]
        at appeng.crafting.v2.CraftingContext.doWork(CraftingContext.java:291) ~[CraftingContext.class:?]
        at appeng.crafting.v2.CraftingJobV2.simulateFor(CraftingJobV2.java:203) ~[CraftingJobV2.class:?]
        at appeng.hooks.TickHandler.lambda$onTick$1(TickHandler.java:173) ~[TickHandler.class:?]
        at java.util.Collection.removeIf(Collection.java:414) [?:1.8.0_332]
        at appeng.hooks.TickHandler.onTick(TickHandler.java:173) [TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_867_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by xfpuls** [comment]
除去编程器电路之后 就变回正常发配物品了

**Comment by reobf** [comment]
能提供log文件吗

**Comment by reobf** [comment]
如果使用的是0.0.18之前的版本（准确地说是从0.0.17p1以及以下的存档  升级到 0.0.17p2到0.0.17p16之间）
也同时使用了多方块大型编程电路提供器
这是已知的bug，升级到0.0.18就好

如果不是，或者升级后依然出问题
希望能提供一下log文件

**Comment by xfpuls** [comment]
> 如果使用的是0.0.18之前的版本（准确地说是从0.0.17p1以及以下的存档 升级到 0.0.17p2到0.0.17p16之间） 也同时使用了多方块大型编程电路提供器 这是已知的bug，升级到0.0.18就好
> 
> 如果不是，或者升级后依然出问题 希望能提供一下log文件

版本是2.6.1 我是从0.017p9升级到18p2 但是升级完还是一样有这个问题

**Comment by xfpuls** [comment]
> 如果使用的是0.0.18之前的版本（准确地说是从0.0.17p1以及以下的存档 升级到 0.0.17p2到0.0.17p16之间） 也同时使用了多方块大型编程电路提供器 这是已知的bug，升级到0.0.18就好
> 
> 如果不是，或者升级后依然出问题 希望能提供一下log文件

并没有使用多方块结构的提供器
[2024-08-05-1.log.gz](https://github.com/user-attachments/files/16490245/2024-08-05-1.log.gz)
log文件是这个吗

**Comment by reobf** [comment]
出现报错后 发log/latest.log
此外请问mod版本？
整合包版本是251、260还是261？

**Comment by reobf** [comment]
此外能发一下存档吗?
如果存档不大，可以直接发存档文件到网盘，或者->https://www.wenshushu.cn/

**Comment by reobf** [comment]
成功复现了 感谢你提供的存档
应该是和最新版ae有点冲突 我试试看能不能适配
如果想立刻解决这个问题就换回261原装ae
 
你用的mod有很多不是261原装的，都是近几天发布的新版本
建议不要自行更新mod版本 尤其是ae这种 除非有你非常感兴趣的新功能
zpbugfix是针对261原装的，如果你自行更新了也不建议安装

**Comment by xfpuls** [comment]
> 成功复现了 感谢你提供的存档 应该是和最新版ae有点冲突 我试试看能不能适配 如果想立刻解决这个问题就换回261原装ae
> 
> 你用的mod有很多不是261原装的，都是近几天发布的新版本 建议不要自行更新mod版本 最新版mod很多不稳定 兼容性也不好 尤其是ae这种。 除非有你非常感兴趣的新功能 zpbugfix是针对261原装的，如果你自行更新了也不建议安装

感谢你的解惑 那我先暂时不用这个功能先等适配再去弄弄 或者我试试回退ae版本有没有问题在去尝试使用

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p3-beta
试试看吧

**Comment by xfpuls** [comment]
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/v0.0.18p3-beta 试试看吧


完美解决了 感谢感谢
